name: Web PrivPropRes(Inside)4

on:
  workflow_run:
    workflows: ["Web PrivPropRes(Inside)2"]
    types:
      - completed

jobs:
  followupjob3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install other dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools==57.5.0
          
      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install -r requirements.txt
          # If you want to avoid using the 2to3 tool, ensure that your dependencies are Python 3 compatible.

      - name: Run web scraping
        run: |
          python PrivatePropRes_Inside4.py 

      - name: Archive CSV file
        uses: actions/upload-artifact@v2
        with:
          name: PrivatePropRes(Inside)4.csv
          path: PrivatePropRes(Inside)4.csv
